eval_benchmarker:
  ros__parameters: 
    config:
      coords:
        metric: "L2"
        criterion: "LowerThan"
        criterion_args: [1.0]

      features:
        metric: "L2"
        criterion: "MinRatio"
        criterion_args: [0.85]

      # features:
      #   metric: "L2"
      #   criterion: "LowerThan"
      #   criterion_args: [230.0]

# [node-1] Average accuracy: 0.9999061822891235
# [node-1] Average precision: 0.7903174161911011
# [node-1] Average recall: 0.45999675989151
# [node-1] Average F1 score: 0.5784803628921509
# [node-1] Average feature count: 4410.984375
# [node-1] Average true count: 1444.796875
# [node-1] Average positive count: 848.8125
