eval_benchmarker:
  ros__parameters: 
    config:
      coords:
        metric: "L2"
        criterion: "LowerThan"
        criterion_args: [1.41]

      features:
        metric: "Cosine"
        criterion: "MaxRatio"
        criterion_args: [1.0]

# For GreaterThan > criterion_args: [0.82]

# [node-1] Average accuracy: 0.9996296763420105
# [node-1] Average precision: 0.02971714921295643
# [node-1] Average recall: 0.020412838086485863
# [node-1] Average F1 score: 0.02381930686533451
# [node-1] Average feature count: 4095.796875
# [node-1] Average true count: 1812.546875
# [node-1] Average positive count: 1378.625

