eval_benchmarker:
  ros__parameters: 
    config:
      keypoints:
        metric: "L2"
        criterion: "LessThan"
        criterion_args: [2.0]

      features:
        matcher: "LightglueMatcher"
        matcher_args: ["/home/arion/AsteroidMatcherModel.pth"]
        criterion: "GreaterThan"
        criterion_args: [0.01]

      # features:
      #   matcher: "ClassicalMatcher"
      #   matcher_args: ["Cosine"]
      #   criterion: "GreaterThan"
      #   criterion_args: [0.75]

# For GreaterThan > criterion_args: [0.75]

# [node-3] Average accuracy: 0.9998650550842285
# [node-3] Average precision: 0.6729938983917236
# [node-3] Average recall: 0.8289981484413147
# [node-3] Average F1 score: 0.742730975151062
# [node-3] Average feature count: 9367.75
# [node-3] Average true count: 10202.125
# [node-3] Average positive count: 12593.375
# [node-3] Average pixel location error: 5.036327362060547