eval_benchmarker:
  ros__parameters: 
    config:
      keypoints:
        metric: "L2"
        criterion: "LessThan"
        criterion_args: [4.0]

      features:
        matcher: "ClassicalMatcher"
        matcher_args: ["Hamming"]
        criterion: "LessThan"
        criterion_args: [40.0]

eval_vo:
  ros__parameters: 
    config:
      matcher: "ClassicalMatcher"
      matcher_args: ["Hamming"]
      criterion: "LessThan"
      criterion_args: [40.0]