eval_benchmarker:
  ros__parameters: 
    config:
      keypoints:
        metric: "L2"
        criterion: "LessThan"
        criterion_args: [1.0]

      features:
        matcher: "ClassicalMatcher"
        matcher_args: ["Hamming"]
        criterion: "MinRatio"
        criterion_args: [0.8]

eval_vo:
  ros__parameters: 
    config:
      matcher: "ClassicalMatcher"
      matcher_args: ["Hamming"]
      criterion: "MinRatio"
      criterion_args: [0.8]
